version: "3.9"

services:
  database:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "DriveNow"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build:
      context: ./Drive-Now
      dockerfile: Dockerfile
    container_name: drive-now_backend
    ports:
      - "3000:3000"
    volumes:
      - ./Drive-Now:/usr/src/app
    env_file:
      - ./Drive-Now/.env
    networks:
      - backend_network
    depends_on:
      - database

  frontend:
    build:
      context: ./DriveNowFrontend
      dockerfile: Dockerfile
    container_name: drive-now_frontend
    ports:
      - "8080:80"
    networks:
      - backend_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  backend_network:
