version: "3.9"

services:
  database:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432" # Externo 5433, interno 5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "DriveNow"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drive-now_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
